CREATE TABLE CITY (
  ID NUMERIC NOT NULL AUTO_INCREMENT,
  CITY_NAME varchar(255) ,
  state_code varchar(255),
  POSTAL_CODE VARCHAR(255),
  latitude VARCHAR(255),
  county VARCHAR(255),
  LONGITUDE VARCHAR(255),
  PRIMARY KEY (ID)
);